image: node:16.14 #define image for docker

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

test project:
  stage: test
  script:
    - npm install
    - npm test

build project:
  stage: build
  script:
    - npm install
    - CI=false npm run build #if CI=true(default) warning are treated as errors
    - echo "Build successful"
  artifacts:
    paths:
      - build/

# TODO: Set the only rule back to trunk. This has been disabled for testing within the features/ci-auto-deployment
build docker image:
  dependencies:
    - build project
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      alias: docker

  #variables:
  #  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: build
  script:
    - echo $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/l4p1n/646-meet-my-needs:latest .
    - docker push $CI_REGISTRY/l4p1n/646-meet-my-needs:latest

#deploy docker image:
#  image: debian:bullseye
#  script:
#    - echo Deploying docker image to the remote server
