version: "3.7"

services:
  database:
    image: postgres:13.6-bullseye
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=meetmyneeds
    volumes:
      - pgsql_data:/var/lib/postgresql/data

  dbmate:
    image: amacneil/dbmate:1.14.0
    command: ["-v"]
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/meetmyneeds?sslmode=disable
      - DBMATE_NO_DUMP_SCHEMA=1
    volumes:
      - ./db:/db

volumes:
  pgsql_data: {}
