version: "3.7"

services:
  react:
    build:
      .

  database:
    image: postgres:13.6-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meetmyneeds
    volumes:
      - pgsql_data:/var/lib/postgresql/data

volumes:
  pgsql_data: {}